# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fermilab Coding Club
email: beau@fnal.gov
description: >- # this means to ignore newlines until "baseurl:"
  Blog style site for keeping Fermilab Coding Club members up to date
  on meetings and topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fermilabcoding.club" # the base hostname & protocol for your site, e.g. http://example.com
list_title: "Next Meeting - March 12th in the Black Hole (WH2NW)"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
